# Welcome to Jekyll!

title: mjelen.eu
description: >- # this means to ignore newlines until "baseurl:"
  One more attempt to set up a blog.
baseurl: ""
url: "https://mjelen.eu"
twitter_username: marek_jelen
github_username:  marekjelen

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
